spring:
  application:
    name: railway-auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:${HOME}/Sites/railways/railway-secrets/auth-secrets/auth-${spring.profiles.active}.properties

server:
  port: 8080
